import mongoose from 'mongoose';

const cvSchema = new mongoose.Schema({
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true
    },
    versionName: {
        type: String,
        required: [true, 'Version name is required'],
        trim: true
    },
    description: {
        type: String,
        trim: true
    },
    // Store snapshot of profile data at time of CV creation
    profileSnapshot: {
        personalInfo: {
            fullName: String,
            phone: String,
            email: String,
            address: String,
            city: String,
            country: String,
            linkedin: String,
            github: String,
            website: String,
            summary: String
        },
        education: [{
            institution: String,
            degree: String,
            field: String,
            startDate: Date,
            endDate: Date,
            current: Boolean,
            gpa: String,
            achievements: [String]
        }],
        workExperience: [{
            company: String,
            position: String,
            location: String,
            startDate: Date,
            endDate: Date,
            current: Boolean,
            responsibilities: [String],
            achievements: [String]
        }],
        projects: [{
            name: String,
            description: String,
            technologies: [String],
            url: String,
            github: String,
            startDate: Date,
            endDate: Date
        }],
        skills: {
            technical: [{
                name: String,
                category: String,
                proficiency: String
            }],
            soft: [{
                name: String,
                proficiency: String
            }]
        },
        certifications: [{
            name: String,
            issuer: String,
            date: Date,
            expirationDate: Date,
            url: String
        }],
        languages: [{
            name: String,
            proficiency: String
        }]
    },
    isDefault: {
        type: Boolean,
        default: false
    },
    generatedDate: {
        type: Date,
        default: Date.now
    },
    // LaTeX code generated by n8n
    latexCode: {
        type: String,
        trim: true
    },
    // For future PDF storage
    filePath: {
        type: String,
        trim: true
    },
    fileSize: {
        type: Number
    },
    usageCount: {
        type: Number,
        default: 0
    },
    // Reference to the job application this CV was generated for
    jobApplication: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'JobApplication'
    }
}, {
    timestamps: true
});

// Ensure only one default CV per user
cvSchema.pre('save', async function (next) {
    if (this.isDefault && this.isModified('isDefault')) {
        await this.constructor.updateMany(
            { user: this.user, _id: { $ne: this._id } },
            { $set: { isDefault: false } }
        );
    }
    next();
});

// Index for efficient queries
cvSchema.index({ user: 1, isDefault: 1 });
cvSchema.index({ user: 1, generatedDate: -1 });

// Virtual for display name
cvSchema.virtual('displayName').get(function () {
    const date = new Date(this.generatedDate).toLocaleDateString('fr-FR', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
    });
    return `${this.versionName} (${date})`;
});

// Method to extract skills for quiz generation
cvSchema.methods.extractSkills = function () {
    const skills = [];

    if (this.profileSnapshot.skills.technical) {
        skills.push(...this.profileSnapshot.skills.technical.map(s => s.name));
    }

    if (this.profileSnapshot.skills.soft) {
        skills.push(...this.profileSnapshot.skills.soft.map(s => s.name));
    }

    return skills;
};

// Method to get experience keywords
cvSchema.methods.extractExperienceKeywords = function () {
    const keywords = new Set();

    // From work experience
    if (this.profileSnapshot.workExperience) {
        this.profileSnapshot.workExperience.forEach(exp => {
            if (exp.position) keywords.add(exp.position);
            if (exp.responsibilities) {
                exp.responsibilities.forEach(r => {
                    // Extract key terms (simple word extraction)
                    r.split(' ').forEach(word => {
                        if (word.length > 4) keywords.add(word.toLowerCase());
                    });
                });
            }
        });
    }

    // From projects
    if (this.profileSnapshot.projects) {
        this.profileSnapshot.projects.forEach(proj => {
            if (proj.technologies) {
                proj.technologies.forEach(tech => keywords.add(tech));
            }
        });
    }

    return Array.from(keywords);
};

// Method to increment usage count
cvSchema.methods.incrementUsage = async function () {
    this.usageCount += 1;
    await this.save();
};

const CV = mongoose.model('CV', cvSchema);

export default CV;
